### ISSUE TITLE
NameError: global name 'history' is not defined

### ISSUE THREAD

**Issue by THE-cattail** [nlml/bpm2#2]
I got this message when I ran 'python2 fit_nn.py'. Is there something I missed to do before running it?
```
Traceback (most recent call last):
  File "fit_nn.py", line 102, in <module>
    history, model = fit_model(model)
  File "fit_nn.py", line 89, in fit_model
    loss = history.history['val_loss'][0]
NameError: global name 'history' is not defined
```

**Comment by nlml** [comment]
Maybe change `history.history` to `histories[-1].history` or maybe just `histories[-1]`

This code is quite old and I don't really have time to maintain it at the moment. But feel free to submit a PR if you do fix this.

**Comment by THE-cattail** [comment]
Thank you for answering! The program worked correctly after I change the code to `histories[-1].history`. I will submit the PR later!

**Comment by catsworld** [comment]
Another problem is what should I do to get BPM of a new .wav file if I has already get `Xy_train.dump` and `Xy_vali.dump` as well as running `fit_nn.py` on them?
